travis:
  secure:
    BINSTAR_TOKEN: s0E4rOTZIKV4V/fVW8iXGHU4h5wxOA9+3q1oJhgfSeYJ1WidS3POgu4fN3IdlNgOkWNml17k5e80v1/vYIJMDZQv8Rki39z0uofH7n4VZpqGH/2zsPHjS4JUHQxrF1jqi7o2Y+vv9nlLZrucnIUpYkNrOo5h4WTSlAj9BgabFm8W2RdLKoIkxYOc4lb3d8N6hdP596Mj5yt4bVkVtNDd8DJ7OA5TiryMx4bFqLdPDIDmrjndu0d73oMVyHSoUZ3A7DzjC0rtINfinv8p+ESfv0pti7hfaGWmPPBoAIsnQOaPKqi+USV04iptVkPDhTtDVvNUUTldWbe715yN46yj6N9XxRfcn9qmx02EW/F4fT/j5i1kYsjS8md3CLlJMY6IWPF+5d7IswLMJv1jX0SxIYm5iUkt2SK5oUpBPOfW1Pi/VfHm3zFdMK8Ub8lrT/th46fTVGqvvgh9oAfzVF15OSb2fn88g6034t7o2qbxB/RD/9u6sfZ7lthQS0vNwuz7sYdge+vCK6iI5G9fmFIJ8S9LWpbffiDAR3YVAFcltNWw39n5YYWgheENUKQKKAtHiaUOACdlmHhTwYQkz49+MexKsdeyPiAM5qVhm47+fxUJzBDWebf/3j8hZ2yXW0T4K7nMfRifW0NXeHNfe/hdCVhabIDPLJttUF3AhZs41Ys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
